FA.JustBlog.Web/Areas/Admin/Controllers/CommentController.cs
using AutoMapper;
using FA.JustBlog.Core.Entities;
using FA.JustBlog.Services.Comments;
using FA.JustBlog.ViewModels.Comments;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace FA.JustBlog.Web.Areas.Admin.Controllers
{
    public class CommentController : BaseController
    {
        private readonly ICommentServices commentServices;
        private readonly IMapper mapper;
        private readonly UserManager<AppUser> userManager;

        public CommentController(ICommentServices commentServices, IMapper mapper, UserManager<AppUser> userManager)
        {
            this.commentServices = commentServices;
            this.mapper = mapper;
            this.userManager = userManager;
        }

        public IActionResult Index(int id)
        {
            ViewBag.PostId = id;
            return View(commentServices.GetCommentsForPost(id));
        }

        [HttpGet]
        public IActionResult Create(int postId)
        {
            ViewBag.PostId = postId;
            CreateCommentViewModel comment = new CreateCommentViewModel();
            return View(comment);
        }


        [HttpPost]
        public IActionResult Create(CreateCommentViewModel comment)
        {
            if (ModelState.IsValid)
            {
                commentServices.Create(comment);
                return RedirectToAction("Index", new {id=comment.PostId});
            }
            return View(comment);
        }


        public IActionResult Edit(int id, int postId)
        {
            ViewBag.PostId = postId;
            var comment = commentServices.Find(id);
            if (comment == null)
            {
                return NotFound();
            }
            return View(mapper.Map<CreateCommentViewModel>(comment));
        }


        [HttpPost]
        public IActionResult Edit(CreateCommentViewModel comment)
        {
            if (ModelState.IsValid)
            {
                commentServices.Update(comment);
                return RedirectToAction("Index", new { id = comment.PostId });
            }
            return View(comment);
        }


        public IActionResult Delete(int id, int postId)
        {
            ViewBag.PostId = postId;
            var category = commentServices.Find(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }


        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id, int postId)
        {
            commentServices.Delete(id);
            return RedirectToAction("Index", new {id=postId});
        }

    }
}

FA.JustBlog.Web/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace FA.JustBlog.Web.Areas.Admin.Controllers
{
    public class HomeController : BaseController
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

FA.JustBlog.Web/Controllers/CategoryController.cs
using FA.JustBlog.Services.Posts;
using FA.JustBlog.Services.Tags;
using Microsoft.AspNetCore.Mvc;

namespace FA.JustBlog.Web.Controllers
{
    public class CategoryController : Controller
    {
        private readonly IPostServices postServices;
        private readonly ITagServices tagServices;

        public CategoryController(IPostServices postServices, ITagServices tagServices)
        {
            this.postServices = postServices;
            this.tagServices = tagServices;
        }

        public IActionResult Index(string name)
        {
            ViewBag.CategoryName = name;
            ViewBag.Tags = tagServices.ListStringTagByCategory(name);
            return View(postServices.GetPostsByCategory(name));
        }

    }
}

FA.JustBlog.Web/Controllers/HomeController.cs
using FA.JustBlog.Services.Categories;
using FA.JustBlog.Services.Posts;
using FA.JustBlog.Services.Tags;
using FA.JustBlog.Web.Models;
using Microsoft.AspNetCore.Mvc;
using ReflectionIT.Mvc.Paging;
using System.Diagnostics;

namespace FA.JustBlog.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly IPostServices postServices;
        private readonly ICategoryServices categoryServices;

        public HomeController(IPostServices postServices, ICategoryServices categoryServices)
        {
            this.postServices = postServices;
            this.categoryServices = categoryServices;
           
        }

        public IActionResult Index(int pageIndex=1)
        {
          
            var posts = postServices.GetAllPostReview().OrderBy(p => p.ModifiedOn);
            var model = PagingList.Create(posts, 3, pageIndex);
            return View(model);
        }

        public IActionResult Details(int id)
        {
            ViewBag.ListTag = postServices.GetTagNameOfPost(id);
            var post = postServices.Find(id);
            var categoryName= postServices.CategoryNameByPost(id);
            post.Category.Name = categoryName;
            return View(post);
        }


        //public ActionResult Menu()
        //{
        //    return PartialView("_Menu", categoryServices.GetAll());
        //}


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FA.JustBlog.Web/Controllers/PostController.cs
using FA.JustBlog.Services.Comments;
using FA.JustBlog.Services.Posts;
using Microsoft.AspNetCore.Mvc;

namespace FA.JustBlog.Web.Controllers
{
    public class PostController : Controller
    {
        private readonly IPostServices postServices;
        private readonly ICommentServices commentServices;

        public PostController(IPostServices postServices, ICommentServices commentServices)
        {
            this.postServices = postServices;
            this.commentServices = commentServices;
        }

        
        public IActionResult Details( int year, int month, string url)
        {
            var post = postServices.FindPost(year, month, url);
            ViewBag.ListTag = postServices.GetTagNameOfPost(post.Id);
            var categoryName = postServices.CategoryNameByPost(post.Id);
            post.Category.Name = categoryName;
            return View(post);
        }

        public IActionResult GetPostByTag(string name)
        {
            ViewBag.TagName = name;
            return View(postServices.GetPostsByTag(name));
        }

        
        public JsonResult AddComment(int PostId, string CommentText)
        {
            var comment=commentServices.AddComment(PostId, CommentText);
            return Json(comment);
        }
    }
}

FA.JustBlog.Web/Views/Home/Details.cshtml
@inject FA.JustBlog.Services.Comments.ICommentServices commentServices
@model FA.JustBlog.Core.Entities.Post
@{
    ViewData["Title"] = "Post Details";
    List<string> tags=ViewBag.ListTag;
    var listComment = commentServices.GetCommentsOfPostForUser(Model.Id);
}
@section Scripts{
    <script>
        $(document).ready(function () {
            $('.btnAddComment').off('click').on('click', function () {
                $.ajax({
                    url: '/Post/AddComment',
                    data: { PostId: $(this).data('id'), CommentText: $('#commnenttext').val() },
                    dataType: 'json',
                    type: 'POST',
                    success: function (res) {
                        var str="<li class='media'><a href='#' class='pull-left'><img src='https://bootdey.com/img/Content/user_1.jpg' alt='' class='img-circle'</a><div class='media-body'><span class='text-muted pull-right' style='float:right'><small class='text-muted'>";
                        str+=res.ModifiedOn+"</small></span><strong class='text-success'>res.Name</strong>";
                        str+="<p>"+res.CommentText+"</p></div></li>"
                        $('#comments').html(str);                           
                    },
                    error: function (res) {
                        console.log(res.responseText);
                        alert("Error has occurred..");
                    }
                })
            });
        })
    </script>
}
@section header{
  <header class="masthead" style="background-image:url('@Url.Content("~/layoutuser/img/about-bg.jpg")')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1 class="text-white">@Model.Title</h1>
            <p class="subheading" style="color:white">
                 Posted @Model.ModifiedOn with rate @Model.Rate by @Model.ViewCount view(s)
            </p>
          </div>
        </div>
      </div>
    </div>
  </header>
}
<div class="post-preview">
    <h5>
       Category: <a asp-controller="Category" asp-action="Index" asp-route-name="@Model.Category.Name">@Model.Category.Name</a>
    </h5>
    <h5>Tag:
    @foreach(var item in tags){
           <a asp-controller="Post" asp-action="GetPostByTag" asp-route-name=@item class="btn btn-dark text-white">@item</a>
    }
    </h5>
    <div>
        @Html.Raw(Model.PostContent)
    </div>
</div>
<div class="container">
<div class="row bootstrap snippets bootdeys">
    <div class="col-12">
        <div class="comment-wrapper">
            <div class="panel panel-info">
                <hr />
                <div class="panel-heading">
                    Comment 
                </div>
                <div class="panel-body">
                    @*<form asp-area="Admin" asp-controller="Comment" asp-action="Create" method="post">*@
                        <textarea class="form-control" placeholder="write a comment..." rows="3" id="commnenttext"></textarea>
                        <br>
                        <button type="button" class="btn btn-info pull-right btnAddComment" data-id="@Model.Id">Post</button>
                   @* </form>*@
                    
                    <div class="clearfix"></div>
                    <hr>
                    <ul class="media-list">
                            @foreach(var item in listComment)
                            {
                                <li class="media">

                                    <a href="#" class="pull-left">
                                        <img src="https://bootdey.com/img/Content/user_1.jpg" alt="" class="img-circle">
                                    </a>
                                    <div class="media-body">
                                        <span class="text-muted pull-right " style="float:right">
                                            <small class="text-muted">@item.ModifiedOn</small>
                                        </span>
                                        <strong class="text-success">@item.Name</strong>
                                        <p>
                                            @item.CommentText
                                        </p>
                                    </div>
                                </li>
                                
                            }
                            <div id="commnents">
                            </div>

                        
                    </ul>
                </div>
            </div>
        </div>

    </div>
</div>
</div>

FA.JustBlog.Web/Views/Home/Index.cshtml
@using ReflectionIT.Mvc.Paging
@model ReflectionIT.Mvc.Paging.PagingList<PostReviewViewModel>
@addTagHelper*,ReflectionIT.Mvc.Paging

@{
    ViewData["Title"] = "Index";
}
@section header{
  <header class="masthead" style="background: url('@Url.Content("~/layoutuser/img/home-bg.jpg")')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1 lass="text-white">Clean Blog</h1>
            <span class="subheading">A Blog Theme by Start Bootstrap</span>
          </div>
        </div>
      </div>
    </div>
  </header>
}
@foreach(var item in Model){
    <div class="post-preview">
          <a href="/Home/Details/@item.Id">
            <h2 class="post-title">
              @item.Title
            </h2>
          </a>
          <p class="post-meta">
              Posted @item.ModifiedOn with rate @item.Rate by @item.ViewCount view(s)
           </p>
         <h5 class="post-subtitle">
              @item.ShortDescription
         </h5>
    </div>
    <hr>
}
<nav aria-label="navigation">
    <vc:pager paging-list="@Model"/>
</nav>
@*<nav aria-label="navigation">
   @await this.Component.InvokeAsync("Pager", new{pagingList=this.Model})
</nav>*@