FA.JustBlog.Web/Areas/Admin/Controllers/CommentController.cs
using AutoMapper;
using FA.JustBlog.Core.Entities;
using FA.JustBlog.Services.Comments;
using FA.JustBlog.ViewModels.Comments;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace FA.JustBlog.Web.Areas.Admin.Controllers
{
    public class CommentController : BaseController
    {
        private readonly ICommentServices commentServices;
        private readonly IMapper mapper;
        private readonly UserManager<AppUser> userManager;

        public CommentController(ICommentServices commentServices, IMapper mapper, UserManager<AppUser> userManager)
        {
            this.commentServices = commentServices;
            this.mapper = mapper;
            this.userManager = userManager;
        }

        public IActionResult Index(int id)
        {
            ViewBag.PostId = id;
            return View(commentServices.GetCommentsForPost(id));
        }

        [HttpGet]
        public IActionResult Create(int postId)
        {
            ViewBag.PostId = postId;
            CreateCommentViewModel comment = new CreateCommentViewModel();
            return View(comment);
        }


        [HttpPost]
        public IActionResult Create(CreateCommentViewModel comment)
        {
            if (ModelState.IsValid)
            {
                commentServices.Create(comment);
                return RedirectToAction("Index", new {id=comment.PostId});
            }
            return View(comment);
        }


        public IActionResult Edit(int id, int postId)
        {
            ViewBag.PostId = postId;
            var comment = commentServices.Find(id);
            if (comment == null)
            {
                return NotFound();
            }
            return View(mapper.Map<CreateCommentViewModel>(comment));
        }


        [HttpPost]
        public IActionResult Edit(CreateCommentViewModel comment)
        {
            if (ModelState.IsValid)
            {
                commentServices.Update(comment);
                return RedirectToAction("Index", new { id = comment.PostId });
            }
            return View(comment);
        }


        public IActionResult Delete(int id, int postId)
        {
            ViewBag.PostId = postId;
            var category = commentServices.Find(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }


        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id, int postId)
        {
            commentServices.Delete(id);
            return RedirectToAction("Index", new {id=postId});
        }

    }
}

FA.JustBlog.Web/Areas/Admin/Controllers/PostController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using FA.JustBlog.Services.Posts;
using FA.JustBlog.Services.Categories;
using FA.JustBlog.ViewModels.Posts;
using AutoMapper;
using FA.JustBlog.Web.Areas.Admin.Views.Shared.Components.SearchBar;


namespace FA.JustBlog.Web.Areas.Admin.Controllers
{
    
    public class PostController : BaseController
    {
        private readonly IPostServices postServices;
        private readonly ICategoryServices categoryServices;
        private readonly IMapper mapper;

        public PostController(IPostServices postServices, ICategoryServices categoryServices, IMapper mapper)
        {
            this.postServices = postServices;
            this.categoryServices = categoryServices;
            this.mapper = mapper;
        }

        public IActionResult Index(string Search = "", int pg = 1)
        {
            var posts = new List<PostViewModel>();
            if (Search != null && Search != "")
            {
                posts = postServices.Search(Search);
            }
            else
            {
                posts = postServices.GetAll();
            }
            const int pageSize = 10;
            int recsCount = posts.Count();
            int resSkip = (pg - 1) * pageSize;
            List<PostViewModel> resPost = posts.Skip(resSkip).Take(pageSize).ToList();
            SPager SearchPager = new SPager(recsCount, pg, pageSize)
            {
                Action = "Index",
                Controller = "Post",
                Search = Search
            };
            ViewBag.SearchPager = SearchPager;
            return View(resPost);
        }


        public IActionResult Details(int id)
        {
            var post = postServices.Find(id);
            if (post == null)
            {
                return NotFound();
            }
            return View(post);
        }

        public IActionResult Create()
        {
            var post = new CreatePostViewModel();
            ViewData["CategoryId"] = new SelectList(categoryServices.GetAll(), "Id", "Name");
            return View(post);
        }

        [HttpPost]
        public IActionResult Create(CreatePostViewModel post)
        {
            if (ModelState.IsValid)
            {
                postServices.Create(post);
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(categoryServices.GetAll(), "Id", "Name");
            return View(post);
        }

        public IActionResult Edit(int id)
        {
            var post = postServices.Find(id);
            if (post == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(categoryServices.GetAll(), "Id", "Name", post.CategoryId);
            var model = mapper.Map<CreatePostViewModel>(post);
            model.Tags = postServices.StringTagOfPost(id);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(CreatePostViewModel post)
        {
            if (ModelState.IsValid)
            {              
                postServices.Update(post);  
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(categoryServices.GetAll(), "Id", "Name", post.CategoryId);
            return View(post);
        }

        public IActionResult Delete(int id)
        {
            var post = postServices.Find(id);
            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            var post = postServices.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

FA.JustBlog.Web/Areas/Admin/Views/Shared/Components/SearchBar/SearchBarViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace FA.JustBlog.Web.Areas.Admin.Views.Shared.Components.SearchBar
{
    public class SearchBarViewComponent:ViewComponent
    {
        public SearchBarViewComponent()
        {

        }

        public IViewComponentResult Invoke(SPager SearchPager)
        {
            return View("Default", SearchPager);
        }
    }
}

FA.JustBlog.Web/Controllers/PostController.cs
using FA.JustBlog.Services.Comments;
using FA.JustBlog.Services.Posts;
using Microsoft.AspNetCore.Mvc;

namespace FA.JustBlog.Web.Controllers
{
    public class PostController : Controller
    {
        private readonly IPostServices postServices;
        private readonly ICommentServices commentServices;

        public PostController(IPostServices postServices, ICommentServices commentServices)
        {
            this.postServices = postServices;
            this.commentServices = commentServices;
        }

        
        public IActionResult Details( int year, int month, string url)
        {
            var post = postServices.FindPost(year, month, url);
            ViewBag.ListTag = postServices.GetTagNameOfPost(post.Id);
            var categoryName = postServices.CategoryNameByPost(post.Id);
            post.Category.Name = categoryName;
            return View(post);
        }

        public IActionResult GetPostByTag(string name)
        {
            ViewBag.TagName = name;
            return View(postServices.GetPostsByTag(name));
        }

        
        public JsonResult AddComment(int PostId, string CommentText)
        {
            var comment=commentServices.AddComment(PostId, CommentText);
            return Json(comment);
        }
    }
}

FA.JustBlog.Web/Areas/Admin/Views/Post/Create.cshtml
@model CreatePostViewModel

@{
    ViewData["Title"] = "Create";
    string[] errorMessages = ViewBag.ErrorMessages;
}
@section scripts{
    <script>  
        
        CKEDITOR.replace("editor1");  
       
    </script>
}

<h1>Create</h1>
<hr />
@if (errorMessages != null)
        {
            <div class="alert alert-danger">
                <ul>
                    @foreach (var error in errorMessages)
                    {
                        <li>@error</li>
                    }
                </ul>
            </div>
        }
<div class="row">
    <div class="col-md-12">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" onchange = "changeUrl('Title','UrlSlug')" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UrlSlug" class="control-label"></label>
                <input asp-for="UrlSlug" class="form-control" readonly/>
                <span asp-validation-for="UrlSlug" class="text-danger"></span>
            </div>
             <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class ="form-control" asp-items="ViewBag.CategoryId"></select>
            </div> 
            <div class="form-group">
                <label asp-for="ShortDescription" class="control-label"></label>
                <textarea asp-for="ShortDescription" class="form-control" rows="5"></textarea>
                <span asp-validation-for="ShortDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PostContent" class="control-label"></label>
                <textarea asp-for="PostContent" id="editor1" rows="5"></textarea>
                <span asp-validation-for="PostContent" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tags" class="control-label"></label>
                <input asp-for="Tags" class="form-control" />
                <span asp-validation-for="Tags" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Published" /> @Html.DisplayNameFor(model => model.Published)
                </label>
            </div>           
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <select name="Status" class="form-select">                   
                   <option selected="selected" value="@Model.Status">@Model.Status</option>
                        @if(@Model.Status==0){
                             <option>Enable</option>
                        }
                        else{
                            <option>Disable</option>
                        }                                     
                </select>
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@*@section Scripts {
   
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}*@

FA.JustBlog.Web/Areas/Admin/Views/Post/Delete.cshtml
@model FA.JustBlog.Core.Entities.Post

@{
    ViewData["Title"] = "Delete";
    string[] errorMessages = ViewBag.ErrorMessages;
}

<h1>Delete</h1>
@if(errorMessages != null)
        {
            <div class="alert alert-danger">
                <ul>
                    @foreach (var error in errorMessages)
                    {
                        <li>@error</li>
                    }
                </ul>
            </div>
        }
<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Post</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ShortDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ShortDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PostContent)
        </dt>
        <dd class = "col-sm-10">
             @Html.Raw(Model.PostContent)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UrlSlug)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UrlSlug)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Published)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Published)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ViewCount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ViewCount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RateCount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RateCount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalRate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalRate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedOn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedOn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ModifiedOn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ModifiedOn)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

FA.JustBlog.Web/Areas/Admin/Views/Post/Details.cshtml
@model FA.JustBlog.Core.Entities.Post

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Post</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ShortDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ShortDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PostContent)
        </dt>
        <dd class = "col-sm-10">
             @Html.Raw(Model.PostContent)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UrlSlug)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UrlSlug)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Published)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Published)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ViewCount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ViewCount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RateCount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RateCount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalRate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalRate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedOn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedOn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ModifiedOn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ModifiedOn)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

FA.JustBlog.Web/Areas/Admin/Views/Post/Edit.cshtml
@model CreatePostViewModel

@{
    ViewData["Title"] = "Edit";
    string[] errorMessages = ViewBag.ErrorMessages;
}
@section scripts{
    <script>  
        CKEDITOR.replace("editor1");   
</script>
}

<h1>Edit</h1>
<hr />
@if (errorMessages != null)
        {
            <div class="alert alert-danger">
                <ul>
                    @foreach (var error in errorMessages)
                    {
                        <li>@error</li>
                    }
                </ul>
            </div>
        }
<div class="row">
    <div class="col-md-12">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UrlSlug" class="control-label"></label>
                <input asp-for="UrlSlug" class="form-control" />
                <span asp-validation-for="UrlSlug" class="text-danger"></span>
            </div>
             <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class ="form-control" asp-items="ViewBag.CategoryId"></select>
            </div> 
            <div class="form-group">
                <label asp-for="ShortDescription" class="control-label"></label>
                <textarea asp-for="ShortDescription" class="form-control" rows="5"></textarea>
                <span asp-validation-for="ShortDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PostContent" class="control-label"></label>
                <textarea asp-for="PostContent" id="editor1" ></textarea>
                <span asp-validation-for="PostContent" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tags" class="control-label"></label>
                <input asp-for="Tags" class="form-control" />
                <span asp-validation-for="Tags" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Published" /> @Html.DisplayNameFor(model => model.Published)
                </label>
            </div>           
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <select name="Status" class="form-select">                   
                   <option selected="selected" value="@Model.Status">@Model.Status</option>
                        @if(@Model.Status==0){
                             <option>Enable</option>
                        }
                        else{
                            <option>Disable</option>
                        }                                     
                </select>
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@*@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}*@

FA.JustBlog.Web/Areas/Admin/Views/Post/Index.cshtml
@model IEnumerable<PostViewModel>


@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create" class="btn btn-success">Create New</a>
</p>

<vc:search-bar search-pager="@ViewBag.SearchPager">
</vc:search-bar>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedOn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ModifiedOn)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedOn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ModifiedOn)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>|
                <a asp-controller="Comment" asp-action="Index" asp-route-id="@item.Id">Comment</a>
            </td>
        </tr>
}
    </tbody>
</table>